# Generated by Django 4.2.30 on 2026-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdownloadlog',
            name='source',
            field=models.CharField(choices=[('azure_blob', 'Azure Blob'), ('adore', 'Adore'), ('goapi', 'GOAPI'), ('sharepoint', 'SharePoint'), ('other', 'Other')], default='other', max_length=20, verbose_name='source'),
        ),
    ]
